forge "http://forge.puppetlabs.com"

mod 'stdlib', :git => "https://github.com/puppetlabs/puppetlabs-stdlib.git"
mod 'nginx', :git => "https://github.com/jfryman/puppet-nginx.git"
mod 'php', :git => "https://github.com/example42/puppet-php"
mod 'mysql', :git => "https://github.com/puppetlabs/puppetlabs-mysql.git"
mod 'n98magerun', :git => "https://github.com/adam-paterson/puppet-n98magerun.git"
